### ISSUE TITLE
Use order.store and not Store.current

### ISSUE THREAD

**Issue by krtschmr** [hefan/spree_sofort#11]
The Service Class is using 

` base_url = "http://#{Spree::Store.current.url}"`. To be cool with Spree 3.1+ and multistore it should be changed to 

`base_url = "http://#{@order.store.url).first}"` or even better (using the first URL) `base_url = "http://#{@order.store.url.split(/\r$/).first}"`

Then we can make the notification_url `    notification_url = "#{base_url}/sofort/status"
`

**Comment by hefan** [comment]
ok, didn;t know that. fixed with your pull request:
f3b6d0d6a0bb3d6447f210cabda4325e61b596ec
