### ISSUE TITLE
NoMethodError in Spree::SofortController#success

### ISSUE THREAD

**Issue by mikosh** [hefan/spree_sofort#13]
Using Spree 3.2.1

Problem file: `sofort_controller.rb`
Line 22:      ` sofort_payment.capture! if sofort_payment.auto_capture?`
`sofort_payment.auto_capture?` generates the NoMethodError

On success redirect from Sofort I get: 

undefined method `auto_capture?' for #<Spree::Payment:0x00000008c61d50>

redirect URL: https://mywebsite.com/sofort/success?sofort_hash=5241a0bc2f9929d5227b1a272d7d2b3c5de8503c357499d4a124d37aa8db57e4

`activemodel (5.0.3) lib/active_model/attribute_methods.rb:433:in `method_missing'
/home/spree/store/shared/bundle/ruby/2.3.0/bundler/gems/spree_sofort-5c239a7500f3/app/controllers/spree/sofort_controller.rb:22:in `success'
actionpack (5.0.3) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.3) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.3) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.3) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.3) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.3) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.3) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.3) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.3) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.3) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.3) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.3) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:725:in `call'
railties (5.0.3) lib/rails/engine.rb:522:in `call'
railties (5.0.3) lib/rails/railtie.rb:193:in `public_send'
railties (5.0.3) lib/rails/railtie.rb:193:in `method_missing'
actionpack (5.0.3) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.3) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:725:in `call'
versioncake (3.1.0) lib/versioncake/rack/middleware.rb:17:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.3) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.3) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.3) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.3) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.3) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.3) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.0.3) lib/rails/engine.rb:522:in `call'
rack (2.0.3) lib/rack/common_logger.rb:33:in `call'
rack (2.0.3) lib/rack/chunked.rb:54:in `call'
rack (2.0.3) lib/rack/content_length.rb:15:in `call'
unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
unicorn (4.8.3) lib/unicorn/http_server.rb:536:in `maintain_worker_count'
unicorn (4.8.3) lib/unicorn/http_server.rb:294:in `join'
unicorn (4.8.3) bin/unicorn:126:in `<top (required)>'
/home/spree/store/shared/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
/home/spree/store/shared/bundle/ruby/2.3.0/bin/unicorn:23:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.3.1@rails500/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1@rails500/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.3.1@rails500/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.1@rails500/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1@rails500/bin/ruby_executable_hooks:15:in `<main>'`

**Comment by hefan** [comment]
thank you for reporting. may have to test it for newer spree versions. i will check these days..

**Comment by hefan** [comment]
ok, should work now.
https://github.com/hefan/spree_sofort/commit/046d8c3cfedbaa5d68d7f9cc830cc34b3afdea82
