### ISSUE TITLE
Support payment profiles

### ISSUE THREAD

**Issue by cshapeshifter** [hefan/spree_sofort#7]
It's a legal requirement in Germany to include a final "confirmation" step at the end of the checkout process, where the customer has the chance to review the order and change any step (including the payment). To make this possible, the payment method must support what Spree refers to as [payment profiles](https://guides.spreecommerce.com/developer/checkout.html#payment-profiles).

I'm not 100% sure if SOFORT supports payment profiiles but I strongly suspect they do, because it's widely used in Germany. Would be cool to see this Gem support this as well.

**Comment by hefan** [comment]
i am not sure where this final confirmation step should take place. Its not possible to store the data for sofort and push it all at once to sofort.

After the redirect to sofort there is only a success or abort message (later transaction status changes aside). So it is not possible to confirm the purchase after entering the data at the sofort page. It is already confirmed then.

Here is the procedure.
https://www.sofort.com/integrationCenter-eng-DE/content/view/full/2513#h3

The other possibility would be to just check sofort as payment and then redirect after the confirmation screen. But it's not what confirmation was meant to be i suppose.

Do you have any sources for the legal requirement in germany for the confirmation step? Sure that it is really mandatory?

**Comment by cshapeshifter** [comment]
Interesting, thanks for this link. This is unexpected.

The legal situation is of course hairy. The important law is in the [BGB § 312j section 2](http://www.gesetze-im-internet.de/englisch_bgb/englisch_bgb.html#p1130) ([German version](http://www.gesetze-im-internet.de/bgb/__312j.html)). It states that *immediately before* the customer initiates the order (i.e. before he pays), the complete order overview must be shown. This matter is presented in a more easily digested form by the Händlerbund in [this PDF, page 4](https://www.haendlerbund.de/hinweisblaetter/finish/1-hinweisblaetter/99-button-loesung)  (German only).

I guess the only solution to this would be to move the redirection to SOFORT from the payment step ahead to the confirmation step. I.e. the workflow for the customer would be:

 * ...
 * pick delivery method
 * pick payment method (SOFORT)
 * view order confirmation page, where everything can be edited (like in screenshot [1] below) and where they have to press "Buy now"
 * When they press "Buy now", redirect to SOFORT for payment and at the end...
 * redirect to the order summary page (screenshot [2])

This way the customer has a chance to review the order before placing the payment and confirming the order.

[1]
![2015-11-15-104234_818x578_scrot](https://cloud.githubusercontent.com/assets/3042135/11168217/c4a930f0-8b85-11e5-8843-131fcac4370a.png)

[2]
![2015-11-15-104617_816x537_scrot](https://cloud.githubusercontent.com/assets/3042135/11168228/1eb01460-8b86-11e5-9f35-7674d852078d.png)

**Comment by hefan** [comment]
OK. This would mean to move the sofort-redirection to (after) the confirm step if
Spree.config.always_include_confirm_step is set to true.
i think this is easily possible. Will have a look into it these days.
Thank you for the suggestion, never thought about it.

**Comment by hefan** [comment]
OK. if Spree.config.always_include_confirm_step is set to true the extension redirects after the confirm step.
Here 58575a73ece3cea8dbece07c79043a8ae9f2a2ca 
and here 5b9dd8b0e0958c8507f2c7d45db599777a73f6c2

Spree.config.always_include_confirm_step is checked in Order.confirmation_required? https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb

I decided to use that instead of overwriting confirmation_required? method in Spree::Order like suggested here:
https://guides.spreecommerce.com/developer/checkout.html
